[tool.poetry]
name = "widget"
version = "0.1.0"
description = ""
authors = ["Elia Bieri <contact@eliabieri.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
componentize-py = "^0.15.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
